CREATE TABLE `grocify`.`user` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email_id` VARCHAR(45) NOT NULL,
  `mobile_no` VARCHAR(10) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `status` BIT(1) NOT NULL DEFAULT 1,
  `metadata` JSON NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `last_login` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE);